/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as InfluencerResetPasswordRouteImport } from './routes/influencer-reset-password'
import { Route as InfluencerLoginRouteImport } from './routes/influencer-login'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as InfluencerRouteRouteImport } from './routes/_influencer/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InfluencerIdRouteImport } from './routes/influencer.$id'
import { Route as CampaignPaymentRouteImport } from './routes/campaign.payment'
import { Route as CampaignNewRouteImport } from './routes/campaign.new'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as InfluencerPortalIndexRouteImport } from './routes/_influencer/portal.index'
import { Route as CampaignPaymentSuccessRouteImport } from './routes/campaign.payment.success'
import { Route as CampaignPaymentCancelRouteImport } from './routes/campaign.payment.cancel'
import { Route as ApiPublicChargilyWebhookRouteImport } from './routes/api/public/chargily-webhook'
import { Route as InfluencerPortalOffersRouteImport } from './routes/_influencer/portal.offers'
import { Route as InfluencerPortalEarningsRouteImport } from './routes/_influencer/portal.earnings'

const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerResetPasswordRoute = InfluencerResetPasswordRouteImport.update({
  id: '/influencer-reset-password',
  path: '/influencer-reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerLoginRoute = InfluencerLoginRouteImport.update({
  id: '/influencer-login',
  path: '/influencer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerRouteRoute = InfluencerRouteRouteImport.update({
  id: '/_influencer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerIdRoute = InfluencerIdRouteImport.update({
  id: '/influencer/$id',
  path: '/influencer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignPaymentRoute = CampaignPaymentRouteImport.update({
  id: '/campaign/payment',
  path: '/campaign/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignNewRoute = CampaignNewRouteImport.update({
  id: '/campaign/new',
  path: '/campaign/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const InfluencerPortalIndexRoute = InfluencerPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => InfluencerRouteRoute,
} as any)
const CampaignPaymentSuccessRoute = CampaignPaymentSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CampaignPaymentRoute,
} as any)
const CampaignPaymentCancelRoute = CampaignPaymentCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => CampaignPaymentRoute,
} as any)
const ApiPublicChargilyWebhookRoute =
  ApiPublicChargilyWebhookRouteImport.update({
    id: '/api/public/chargily-webhook',
    path: '/api/public/chargily-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfluencerPortalOffersRoute = InfluencerPortalOffersRouteImport.update({
  id: '/portal/offers',
  path: '/portal/offers',
  getParentRoute: () => InfluencerRouteRoute,
} as any)
const InfluencerPortalEarningsRoute =
  InfluencerPortalEarningsRouteImport.update({
    id: '/portal/earnings',
    path: '/portal/earnings',
    getParentRoute: () => InfluencerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/favorites': typeof FavoritesRoute
  '/influencer-login': typeof InfluencerLoginRoute
  '/influencer-reset-password': typeof InfluencerResetPasswordRoute
  '/messages': typeof MessagesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campaign/new': typeof CampaignNewRoute
  '/campaign/payment': typeof CampaignPaymentRouteWithChildren
  '/influencer/$id': typeof InfluencerIdRoute
  '/portal/earnings': typeof InfluencerPortalEarningsRoute
  '/portal/offers': typeof InfluencerPortalOffersRoute
  '/api/public/chargily-webhook': typeof ApiPublicChargilyWebhookRoute
  '/campaign/payment/cancel': typeof CampaignPaymentCancelRoute
  '/campaign/payment/success': typeof CampaignPaymentSuccessRoute
  '/portal/': typeof InfluencerPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/favorites': typeof FavoritesRoute
  '/influencer-login': typeof InfluencerLoginRoute
  '/influencer-reset-password': typeof InfluencerResetPasswordRoute
  '/messages': typeof MessagesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campaign/new': typeof CampaignNewRoute
  '/campaign/payment': typeof CampaignPaymentRouteWithChildren
  '/influencer/$id': typeof InfluencerIdRoute
  '/portal/earnings': typeof InfluencerPortalEarningsRoute
  '/portal/offers': typeof InfluencerPortalOffersRoute
  '/api/public/chargily-webhook': typeof ApiPublicChargilyWebhookRoute
  '/campaign/payment/cancel': typeof CampaignPaymentCancelRoute
  '/campaign/payment/success': typeof CampaignPaymentSuccessRoute
  '/portal': typeof InfluencerPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_influencer': typeof InfluencerRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/auth': typeof AuthRouteWithChildren
  '/campaigns': typeof CampaignsRoute
  '/favorites': typeof FavoritesRoute
  '/influencer-login': typeof InfluencerLoginRoute
  '/influencer-reset-password': typeof InfluencerResetPasswordRoute
  '/messages': typeof MessagesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campaign/new': typeof CampaignNewRoute
  '/campaign/payment': typeof CampaignPaymentRouteWithChildren
  '/influencer/$id': typeof InfluencerIdRoute
  '/_influencer/portal/earnings': typeof InfluencerPortalEarningsRoute
  '/_influencer/portal/offers': typeof InfluencerPortalOffersRoute
  '/api/public/chargily-webhook': typeof ApiPublicChargilyWebhookRoute
  '/campaign/payment/cancel': typeof CampaignPaymentCancelRoute
  '/campaign/payment/success': typeof CampaignPaymentSuccessRoute
  '/_influencer/portal/': typeof InfluencerPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/campaigns'
    | '/favorites'
    | '/influencer-login'
    | '/influencer-reset-password'
    | '/messages'
    | '/auth/callback'
    | '/campaign/new'
    | '/campaign/payment'
    | '/influencer/$id'
    | '/portal/earnings'
    | '/portal/offers'
    | '/api/public/chargily-webhook'
    | '/campaign/payment/cancel'
    | '/campaign/payment/success'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/campaigns'
    | '/favorites'
    | '/influencer-login'
    | '/influencer-reset-password'
    | '/messages'
    | '/auth/callback'
    | '/campaign/new'
    | '/campaign/payment'
    | '/influencer/$id'
    | '/portal/earnings'
    | '/portal/offers'
    | '/api/public/chargily-webhook'
    | '/campaign/payment/cancel'
    | '/campaign/payment/success'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_influencer'
    | '/account'
    | '/auth'
    | '/campaigns'
    | '/favorites'
    | '/influencer-login'
    | '/influencer-reset-password'
    | '/messages'
    | '/auth/callback'
    | '/campaign/new'
    | '/campaign/payment'
    | '/influencer/$id'
    | '/_influencer/portal/earnings'
    | '/_influencer/portal/offers'
    | '/api/public/chargily-webhook'
    | '/campaign/payment/cancel'
    | '/campaign/payment/success'
    | '/_influencer/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfluencerRouteRoute: typeof InfluencerRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRouteWithChildren
  CampaignsRoute: typeof CampaignsRoute
  FavoritesRoute: typeof FavoritesRoute
  InfluencerLoginRoute: typeof InfluencerLoginRoute
  InfluencerResetPasswordRoute: typeof InfluencerResetPasswordRoute
  MessagesRoute: typeof MessagesRoute
  CampaignNewRoute: typeof CampaignNewRoute
  CampaignPaymentRoute: typeof CampaignPaymentRouteWithChildren
  InfluencerIdRoute: typeof InfluencerIdRoute
  ApiPublicChargilyWebhookRoute: typeof ApiPublicChargilyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer-reset-password': {
      id: '/influencer-reset-password'
      path: '/influencer-reset-password'
      fullPath: '/influencer-reset-password'
      preLoaderRoute: typeof InfluencerResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer-login': {
      id: '/influencer-login'
      path: '/influencer-login'
      fullPath: '/influencer-login'
      preLoaderRoute: typeof InfluencerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_influencer': {
      id: '/_influencer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof InfluencerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer/$id': {
      id: '/influencer/$id'
      path: '/influencer/$id'
      fullPath: '/influencer/$id'
      preLoaderRoute: typeof InfluencerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/payment': {
      id: '/campaign/payment'
      path: '/campaign/payment'
      fullPath: '/campaign/payment'
      preLoaderRoute: typeof CampaignPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/new': {
      id: '/campaign/new'
      path: '/campaign/new'
      fullPath: '/campaign/new'
      preLoaderRoute: typeof CampaignNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_influencer/portal/': {
      id: '/_influencer/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof InfluencerPortalIndexRouteImport
      parentRoute: typeof InfluencerRouteRoute
    }
    '/campaign/payment/success': {
      id: '/campaign/payment/success'
      path: '/success'
      fullPath: '/campaign/payment/success'
      preLoaderRoute: typeof CampaignPaymentSuccessRouteImport
      parentRoute: typeof CampaignPaymentRoute
    }
    '/campaign/payment/cancel': {
      id: '/campaign/payment/cancel'
      path: '/cancel'
      fullPath: '/campaign/payment/cancel'
      preLoaderRoute: typeof CampaignPaymentCancelRouteImport
      parentRoute: typeof CampaignPaymentRoute
    }
    '/api/public/chargily-webhook': {
      id: '/api/public/chargily-webhook'
      path: '/api/public/chargily-webhook'
      fullPath: '/api/public/chargily-webhook'
      preLoaderRoute: typeof ApiPublicChargilyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_influencer/portal/offers': {
      id: '/_influencer/portal/offers'
      path: '/portal/offers'
      fullPath: '/portal/offers'
      preLoaderRoute: typeof InfluencerPortalOffersRouteImport
      parentRoute: typeof InfluencerRouteRoute
    }
    '/_influencer/portal/earnings': {
      id: '/_influencer/portal/earnings'
      path: '/portal/earnings'
      fullPath: '/portal/earnings'
      preLoaderRoute: typeof InfluencerPortalEarningsRouteImport
      parentRoute: typeof InfluencerRouteRoute
    }
  }
}

interface InfluencerRouteRouteChildren {
  InfluencerPortalEarningsRoute: typeof InfluencerPortalEarningsRoute
  InfluencerPortalOffersRoute: typeof InfluencerPortalOffersRoute
  InfluencerPortalIndexRoute: typeof InfluencerPortalIndexRoute
}

const InfluencerRouteRouteChildren: InfluencerRouteRouteChildren = {
  InfluencerPortalEarningsRoute: InfluencerPortalEarningsRoute,
  InfluencerPortalOffersRoute: InfluencerPortalOffersRoute,
  InfluencerPortalIndexRoute: InfluencerPortalIndexRoute,
}

const InfluencerRouteRouteWithChildren = InfluencerRouteRoute._addFileChildren(
  InfluencerRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CampaignPaymentRouteChildren {
  CampaignPaymentCancelRoute: typeof CampaignPaymentCancelRoute
  CampaignPaymentSuccessRoute: typeof CampaignPaymentSuccessRoute
}

const CampaignPaymentRouteChildren: CampaignPaymentRouteChildren = {
  CampaignPaymentCancelRoute: CampaignPaymentCancelRoute,
  CampaignPaymentSuccessRoute: CampaignPaymentSuccessRoute,
}

const CampaignPaymentRouteWithChildren = CampaignPaymentRoute._addFileChildren(
  CampaignPaymentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfluencerRouteRoute: InfluencerRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRouteWithChildren,
  CampaignsRoute: CampaignsRoute,
  FavoritesRoute: FavoritesRoute,
  InfluencerLoginRoute: InfluencerLoginRoute,
  InfluencerResetPasswordRoute: InfluencerResetPasswordRoute,
  MessagesRoute: MessagesRoute,
  CampaignNewRoute: CampaignNewRoute,
  CampaignPaymentRoute: CampaignPaymentRouteWithChildren,
  InfluencerIdRoute: InfluencerIdRoute,
  ApiPublicChargilyWebhookRoute: ApiPublicChargilyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
